# Generated by Django 5.1.6 on 2026-03-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_app', '0002_chatsession_question_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_from_home', models.BooleanField(default=False)),
                ('part_time', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('stipend_min', models.IntegerField(blank=True, null=True)),
                ('stipend_max', models.IntegerField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=512)),
                ('post_offer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
