# Generated by Django 5.1.6 on 2026-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_app', '0003_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='city',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='part_time',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='post_offer',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='stipend_max',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='stipend_min',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='work_from_home',
        ),
        migrations.AddField(
            model_name='internship',
            name='apply_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='stipend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='skills',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
