# Generated by Django 5.1.6 on 2026-03-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_app', '0004_remove_internship_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='stipend',
            new_name='skills_required',
        ),
    ]
