# Generated by Django 5.1.6 on 2026-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_app', '0005_rename_stipend_internship_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
