# Generated by Django 5.1.6 on 2026-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_app', '0006_internship_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='apply_link',
            field=models.URLField(max_length=1000),
        ),
    ]
